# Using this to deploy instead of Vercel's GitHub integration because the
# actual integration requires a paid Vercel account.

name: Vercel PR Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
jobs:
  pr-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN }}
